**Jupyter Notebook 1 Mini Project**


**1. Introduction**

Briefly describe the project and dataset.

Example:

Objective of analysis
Dataset source (Kaggle, government portal, etc.)
What problem you are trying to solve

2. Data Selection
2.1 Dataset Description
Name of dataset
Source of dataset
Size (rows × columns)

Example:

In [ ]:
import pandas as pd

df = pd.read_csv('/content/sales_data.csv')
df.head()

,Order_ID,Order_Date,Customer_Name,Region,Product,Category,Sales,Quantity,Profit
0,1001,2023-01-05,John Smith,West,Laptop,Technology,1200,2,200
1,1002,2023-01-06,Alice Brown,East,Chair,Furniture,300,3,50
2,1003,2023-01-07,David Lee,South,Phone,Technology,800,1,120
3,1004,2023-01-08,Sarah Wilson,North,Table,Furniture,450,2,70
4,1005,2023-01-09,Michael Scott,West,Printer,Technology,600,1,90

In [ ]:
df.shape

(15, 9)

In [ ]:
import pandas as pd

data = [
[1001,"2023-01-05","John Smith","West","Laptop","Technology",1200,2,200],
[1002,"2023-01-06","Alice Brown","East","Chair","Furniture",300,3,50],
[1003,"2023-01-07","David Lee","South","Phone","Technology",800,1,120],
[1004,"2023-01-08","Sarah Wilson","North","Table","Furniture",450,2,70],
[1005,"2023-01-09","Michael Scott","West","Printer","Technology",600,1,90],
[1006,"2023-01-10","Jim Halpert","East","Desk","Furniture",700,2,100],
[1007,"2023-01-11","Pam Beesly","South","Notebook","Office Supplies",50,5,10],
[1008,"2023-01-12","Dwight Schrute","North","Monitor","Technology",300,1,60],
[1009,"2023-01-13","Angela Martin","West","Keyboard","Technology",150,2,30],
[1010,"2023-01-14","Kevin Malone","East","Mouse","Technology",80,3,20],
[1011,"2023-01-15","Oscar Martinez","South","Pen Set","Office Supplies",40,4,8],
[1012,"2023-01-16","Stanley Hudson","North","Bookshelf","Furniture",500,1,75],
[1013,"2023-01-17","Meredith Grey","West","Tablet","Technology",900,2,150],
[1014,"2023-01-18","Derek Shepherd","East","Chair","Furniture",350,2,60],
[1015,"2023-01-19","Miranda Bailey","South","Printer","Technology",650,1,95]
]

columns = ["Order_ID","Order_Date","Customer_Name","Region","Product","Category","Sales","Quantity","Profit"]

df = pd.DataFrame(data, columns=columns)

# Save as CSV
df.to_csv("sales_data.csv", index=False)

print("File saved as sales_data.csv")

File saved as sales_data.csv

**Dataset Description**

The dataset contains sales transactions including:
Orders
Customers
Products
Revenue details

Example:

Rows: ~10,000

Columns: ~15–20

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       15 non-null     int64
 1   Order_Date     15 non-null     object
 2   Customer_Name  15 non-null     object
 3   Region         15 non-null     object
 4   Product        15 non-null     object
 5   Category       15 non-null     object
 6   Sales          15 non-null     int64
 7   Quantity       15 non-null     int64
 8   Profit         15 non-null     int64
dtypes: int64(4), object(5)
memory usage: 1.2+ KB

| Attribute     | Data Type         | Description             |
| ------------- | ----------------- | ----------------------- |
| Order_ID      | Object            | Unique order identifier |
| Order_Date    | Object → Datetime | Date of purchase        |
| Customer_Name | Object            | Name of customer        |
| Region        | Categorical       | Sales region            |
| Product       | Object            | Product name            |
| Category      | Categorical       | Product category        |
| Sales         | Float             | Revenue generated       |
| Quantity      | Integer           | Units sold              |
| Profit        | Float             | Profit earned           |

**Explanation:**

Object → categorical/text data
Float → numerical continuous
Integer → discrete values

**Attribute Selection & Filtering**

**Selected Attributes:**

Order_Date, Region, Category, Sales, Quantity, Profit

Removed Attributes:

Customer_Name → not required for analysis
Order_ID → unique identifier, not useful for trends

In [ ]:
df = df[['Order_Date', 'Region', 'Category', 'Sales', 'Quantity', 'Profit']]

**Reasoning:**

Focus is on sales trends and performance, not individual customers

**Data Cleaning**

In [ ]:
df.isnull().sum()

Order_Date    0
Region        0
Category      0
Sales         0
Quantity      0
Profit        0
dtype: int64

In [ ]:
df['Sales'].fillna(df['Sales'].mean(), inplace=True)
df['Profit'].fillna(df['Profit'].median(), inplace=True)
df.dropna(inplace=True)

/tmp/ipykernel_4263/3414012257.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sales'].fillna(df['Sales'].mean(), inplace=True)
/tmp/ipykernel_4263/3414012257.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Profit'].fillna(df['Profit'].median(), inplace=True)

**Reasoning:**

Mean/median preserves dataset distribution
Remaining null rows removed

**Remove Duplicates**

In [ ]:
df.drop_duplicates(inplace=True)

**Fix Data Types**

In [ ]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

**Outlier Detection & Removal**

In [ ]:
Q1 = df['Sales'].quantile(0.25)
Q3 = df['Sales'].quantile(0.75)
IQR = Q3 - Q1

df = df[(df['Sales'] >= Q1 - 1.5*IQR) & (df['Sales'] <= Q3 + 1.5*IQR)]

**Reasoning:**

Removes extreme values that may distort analysis

**Data Wrangling**
**Feature Engineering**

Create new column:

In [ ]:
df['Sales_per_Unit'] = df['Sales'] / df['Quantity']

**Extract Date Features**

In [ ]:
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

**Encoding Categorical Variables**

In [ ]:
df = pd.get_dummies(df, columns=['Region', 'Category'])

**Filtering Data**

Example:

In [ ]:
df = df[df['Sales'] > 0]

**Reasoning:**

Removes invalid transactions

**Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['Sales', 'Profit']] = scaler.fit_transform(df[['Sales', 'Profit']])

**Final Dataset **

In [ ]:
df.shape
df.head()
df.describe()

,Order_Date,Sales,Quantity,Profit,Sales_per_Unit,Year,Month
count,15,1.500000e+01,15.000000,1.500000e+01,15.000000,15.0,15.0
mean,2023-01-12 00:00:00,8.881784e-17,2.133333,1.332268e-16,324.777778,2023.0,1.0
min,2023-01-05 00:00:00,-1.313246e+00,1.000000,-1.324576e+00,10.000000,2023.0,1.0
25%,2023-01-08 12:00:00,-7.499914e-01,1.000000,-7.000214e-01,87.500000,2023.0,1.0
50%,2023-01-12 00:00:00,-6.495190e-02,2.000000,-1.145016e-01,300.000000,2023.0,1.0
75%,2023-01-15 12:00:00,6.200876e-01,2.500000,4.222248e-01,550.000000,2023.0,1.0
max,2023-01-19 00:00:00,2.218513e+00,5.000000,2.422750e+00,800.000000,2023.0,1.0
std,NaN,1.035098e+00,1.187234,1.035098e+00,262.280798,0.0,0.0